# Generated by Django 4.0.6 on 2022-07-19 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Food',
            new_name='Foods',
        ),
    ]
